// Code generated by mockery v1.0.0
package adopt

import mock "github.com/stretchr/testify/mock"
import model "github.com/slok/external-dns-aws-adopter/pkg/model"

// RSAdopter is an autogenerated mock type for the RSAdopter type
type RSAdopter struct {
	mock.Mock
}

// Adopt provides a mock function with given fields: _a0
func (_m *RSAdopter) Adopt(_a0 *model.Entry) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Entry) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
